### ISSUE TITLE
Update API 

### ISSUE THREAD

**Issue by dooleydevin** [GrinnellAppDev/DB-iOS#30]
We will need to update the current JSON parsing method so that it reflects the new API. This will snowball into a couple other of pages. The new API can be found here: 

https://appdev.grinnell.edu/api/db/v1/docs/

Specifically, the new dept field will be important to focus on, and we will need to display all titles in the titles array in the detail page (which will require us to expand the height of the cell dynamically).

**Comment by arthurhero** [comment]
Basically finished. Good job!
